### ISSUE TITLE
Привет я тебе кидал свой токен и ты его вставил в код.

### ISSUE THREAD

**Issue by maha4kala001** [xartd0/SKYSMART-ANSWERS#10]
Я пронимаю что этот токен это имя и фамилия пользователь тоесть если я сам буду его использовать то учетелям будет показанно что моё имя и фамилия уже проходит тест?

**Comment by maha4kala001** [comment]
И подскажи пожалуйста как сделать чтоб питон после показания ответов не закрывался или закрывался но спустя не мили секунду

**Comment by xartd0** [comment]
Я твой токен в код не вставлял,все аккаунты новые,проверь еще раз у них начало одинаковое,а чтобы питон не закрывался запускай через cmd python main.py или в скрипте после цикла поставь time.sleep(1000)
