### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by Vodeninja** [xartd0/Skysmart-Answers#11]
скрипт выдает ошибку 
`Traceback (most recent call last):
  File "main.py", line 98, in <module>
    answerparse(taskHash)
  File "main.py", line 24, in answerparse
    roomHash = roomhashjson['roomHash'] # код рума
KeyError: 'roomHash'`
может python не той версии?
Python 3.7.3

**Comment by xartd0** [comment]
Проверь токен и покажи из какой ссылки берешь код румы
