### ISSUE TITLE
Скрипт отправляет ответы не в том порядке

### ISSUE THREAD

**Issue by timoxa0** [xartd0/Skysmart-Answers#12]
При решении некоторых заданий cкрипт/бот отправляет ответы не в том порядке, в каком заполняются.
Видео: https://clck.ru/bAojA
Код комнаты: xovorukise

**Comment by xartd0** [comment]
Спасибо,исправлю.

**Comment by Apkge** [comment]
https://edu.skysmart.ru/lesson/homework/nuhuseduxiza/7

**Comment by Apkge** [comment]
> При решении некоторых заданий cкрипт/бот отправляет ответы не в том порядке, в каком заполняются. Видео: https://clck.ru/bAojA Код комнаты: xovorukise
