### ISSUE TITLE
Проблема с подключением к себе в проект.

### ISSUE THREAD

**Issue by Ouki76** [xartd0/Skysmart-Answers#15]
https://media.discordapp.net/attachments/942393025483644949/970032279932010566/unknown.png?width=960&height=541 
Ошибка в терминале
https://media.discordapp.net/attachments/942393025483644949/970032496043495504/unknown.png?width=960&height=583
Код моей программы.
функция Dadada вызывается на 32 строке.
Мои импорты: 
from time import sleep
from telebot import types, telebot, TeleBot
import requests
import config
import Skysmart
import asyncio
Вроде все приложил. Честно не понимаю, почему не работает. Может ты сможешь мне помочь? И можешь ли ты оставить свои контактные данные, чтобы я если что смог быстро с тобой связаться

**Comment by xartd0** [comment]
Проверь, мб ты удалил headers = {
        'Content-Type': 'application/json',
        'Authorization': token,
        'User-Agent':'User-Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0'
    } 
Поставь это в самом начале после импортов, если не видит, то тогда просто замени на это все headers, вот мой тг https://t.me/xartd012

**Comment by prtolem** [comment]
ты как собрался синхронный телебот использовать с асинхронным кодом?

**Comment by Ouki76** [comment]
> 

https://github.com/OukiLove/SkysmartTelegramBot
Давно уже сделали. Ты немного опоздал

**Comment by prtolem** [comment]
я бы сказал что в коде не так, но я не буду, не хочу тебя обидеть
