### ISSUE TITLE
Проблемы с запуском

### ISSUE THREAD

**Issue by nitr0gen1um** [xartd0/Skysmart-Answers#16]
Привет, я скачал твой скрипт и нажал запуск, прошло 0.7сек и скрипт выполнился, можешь найти меня в тг, у меня к тебе много вопросов) https://t.me/n1tr0gen1um

**Comment by m0n1serrat** [comment]
Согласен, такая же проблема

**Comment by xartd0** [comment]
> Согласен, такая же проблема

Скрипт очень старый и кривой, возможно уже и не работает, может скоро обновлю.

**Comment by xartd0** [comment]
Исправил по фасту, должно теперь работать

**Comment by m0n1serrat** [comment]
![image](https://user-images.githubusercontent.com/108661193/208251904-a31bd1c7-bb9a-4cb4-8089-3bc5165c5f7b.png)

Все равно вылазит какая то ошибка, возможно я что-то делаю не так, если подскажите буду очень благодарен

**Comment by xartd0** [comment]
> ![image](https://user-images.githubusercontent.com/108661193/208251904-a31bd1c7-bb9a-4cb4-8089-3bc5165c5f7b.png)
> 
> Все равно вылазит какая то ошибка, возможно я что-то делаю не так, если подскажите буду очень благодарен

Ты вставляешь ссылку, а нужно название комнаты, это слово в ссылке после /student

**Comment by m0n1serrat** [comment]
Спасибо большое, помогло!

сб, 17 дек. 2022 г., 21:46 Xartd0 ***@***.***>:
