### ISSUE TITLE
Не всё может решить

### ISSUE THREAD

**Issue by vovakolinko** [xartd0/Skysmart-Answers#18]
Снова прив,
код комнаты ```zupubufure```. Ответ на 1, 6-12 не находит

```
Название теста: Задание от 7 февраля, 08:12
Тема: №15 Задание на установление соотвествия


Задание #1
Выполни задание
Какие два из представленных ниже понятий Ольга будет использовать в своём рассказе? Выпиши соответствующие понятия и раскрой их смысл.

Ответы:

---------------

Задание #6
Выполни задание
Рассмотри изображения.

Ответы:

---------------

Задание #7
Выполни задание
Рассмотри изображения.

Ответы:

---------------

Задание #8
Выполни задание
В чём состоит удобство пользования мобильным банкингом? Укажи одно любое преимущество.

Ответы:

---------------

Задание #9
Выполни задание
Чем опасна такая ситуация для личных сбережений пенсионера?

Ответы:

---------------

Задание #10
Выполни задание
Стоит ли Дарье соглашаться на такую работу? Свой ответ поясни.

Ответы:

---------------

Задание #11
Выполни задание
Что может произойти с финансами пенсионерки после того, как она сообщит необходимые данные по телефону?

Ответы:

---------------

Задание #12
Выполни задание
Правильно ли поступил Андрей Борисович? Свой ответ поясни.

Ответы:
```

**Comment by xartd0** [comment]
Да, скрипт надо конечно обновить, я тестил его на не очень большом количестве тестов, поэтому много багов/недоработок.
К сожалению сейчас совсем нет времени на него,

**Comment by vovakolinko** [comment]
А вот и этот тест ...
![IMG_20230214_155926_415.jpg](https://user-images.githubusercontent.com/61107330/218761417-53e1f238-e251-4bf1-abad-f97ca4a0c9e4.jpg)
Ну всё верно нашло, картинку же с сервера не вытягивать. Ошибку можно закрывать

**Comment by xartd0** [comment]
> А вот и этот тест ...
> ![IMG_20230214_155926_415.jpg](https://user-images.githubusercontent.com/61107330/218761417-53e1f238-e251-4bf1-abad-f97ca4a0c9e4.jpg)
> Ну всё верно нашло, картинку же с сервера не вытягивать. Ошибку можно закрывать

Так там самому фотку надо загрузить, такие задания вручную проверяют.

**Comment by vovakolinko** [comment]
Единственное, можно тут добавить сообщение типо "тут картинка". Попробую  реализовать когда будет время (никогда). Код пришлю сюда (только проверь его перед тем как добавлять)

**Comment by vovakolinko** [comment]
```
#Проверь
if soup.find('edu-open-answer', attrs={'id': 'OA1'}): #Ищем <edu-open-answer id="OA1"></edu-open-answer>
    answers.append('Необходимо загрузить файл') #Добавляем
```

**Comment by xartd0** [comment]
> ```
> #Проверь
> if soup.find('edu-open-answer', attrs={'id': 'OA1'}): #Ищем <edu-open-answer id="OA1"></edu-open-answer>
>     answers.append('Необходимо загрузить файл') #Добавляем
> ```

Напиши мне в тг - https://t.me/xartd0000000

**Comment by vovakolinko** [comment]
Исправлено в [последнем (на 14 февр 2023 года) комите](https://github.com/xartd0/Skysmart-Answers/commit/eb4ece2fc95c52f69b16522f76bebcd5102e03da)
