### ISSUE TITLE
Как получить токен skysmart?

### ISSUE THREAD

**Issue by ComandanteZer0** [xartd0/SKYSMART-ANSWERS#2]
Как получить токен skysmart?

**Comment by xartd0** [comment]
![изображение](https://user-images.githubusercontent.com/43171120/151268466-dcd63fd2-e653-461a-a049-b2b41a014db2.png)
Заходишь на любой тест или просто входишь в акк,потом в f12 ищещь в 'Сеть' loadstep uuid и там он будет,как на фотке.

**Comment by maha4kala001** [comment]
![image](https://user-images.githubusercontent.com/98516967/151322971-97827a45-accf-408c-8e31-a1c1a36f90bb.png)
что делать если у меня не так как у тебя

**Comment by xartd0** [comment]
У тебя видимо другой браузер,нажми на Все,рядом с изображение и перезагрузи страницу
