### ISSUE TITLE
Error during getting room: Room request failed with status: 404

### ISSUE THREAD

**Issue by onisonic** [xartd0/Skysmart-Answers#21]
с недавнего времени скрипт начал выдавать следующую ошибку:
![изображение](https://github.com/xartd0/Skysmart-Answers/assets/93402361/0b313a7b-99a9-4b02-a7a3-9a4b3bccc78b)
переустановка не помогла, проверяла на двух разных тестах - на этих обоих тестах одна и та же ошибка, как на скрине

**Comment by xartd0** [comment]
> с недавнего времени скрипт начал выдавать следующую ошибку:
> ![изображение](https://github.com/xartd0/Skysmart-Answers/assets/93402361/0b313a7b-99a9-4b02-a7a3-9a4b3bccc78b)
> переустановка не помогла, проверяла на двух разных тестах - на этих обоих тестах одна и та же ошибка, как на скрине

Об ошибке известно, они поменяли авторизацию, поэтому пока пытаюсь сделать автоматическую авторизацию, но пока можно чисто подставлять bearer token, я вставил пока от тестого аккаунта, но его можно найти в личном аккаунте в header при запросах.

**Comment by xartd0** [comment]
Исправил авторизацию в новом коммите.
