### ISSUE TITLE
можешь пожалуйста  записать видео где говоришь где что найти и куда вставлять а то по отдельности нечего не понятно

### ISSUE THREAD

**Issue by maha4kala001** [xartd0/SKYSMART-ANSWERS#3]

**Comment by xartd0** [comment]
![изображение](https://user-images.githubusercontent.com/43171120/151335291-b16c16be-087f-457f-9cb4-9efd67bd5cc2.png)
Заходишь на любой тест,нажимаешь f12,там сеть и ищешь как на скрине,копируешь token и в коде вставляешь,где 'YOUR TOKEN'

**Comment by maha4kala001** [comment]
я нашёл токен вставил и мне выдаёт вот такую ошибку 
![image](https://user-images.githubusercontent.com/98516967/151355581-d4065f19-7fba-4124-9b3f-19238d79109d.png)

**Comment by xartd0** [comment]
> я нашёл токен вставил и мне выдаёт вот такую ошибку 
> ![image](https://user-images.githubusercontent.com/98516967/151355581-d4065f19-7fba-4124-9b3f-19238d79109d.png)
> 
> 

Ты не установил модуль requests, там вроде написано все.

**Comment by maha4kala001** [comment]
А как его установить?

**Comment by xartd0** [comment]
> А как его установить? 
> 

pip install requests
