### ISSUE TITLE
выдаёт ошибку, что делать?

### ISSUE THREAD

**Issue by C-Boygg** [xartd0/Skysmart-Answers#5]
Traceback (most recent call last):
  File "C:\Users\ilya_\Downloads\gd", line 93, in <module>
    answerparse(taskHash)
  File "C:\Users\ilya_\Downloads\gd", line 22, in answerparse
    roomHash = roomhashjson['roomHash'] # код рума
KeyError: 'roomHash'

в чём может быть проблема (я новичок в питоне, не ругайтесь сильно)

**Comment by xartd0** [comment]
Проблема скорее всего,что вы взяли код рума из неправильной ссылки,ссылка должна быть такая https://edu.skysmart.ru/student/ledotetote  - ledotetote это рандомное имя теста,его и надо отправлять в скрипт и обновите скрипт,я исправил небольшой баг.

**Comment by sqwhh** [comment]
+++тоже самое было

**Comment by florrika** [comment]
а если ссылка https://vimbox.skyeng.ru/kids/math/room/...?homework=true
