### ISSUE TITLE
Не совсем понял с токеом

### ISSUE THREAD

**Issue by C-Boygg** [xartd0/SKYSMART-ANSWERS#6]
вроде нашел штуку с токеном, но че делать чтобы получить токен дальше хз 

![2022-01-29](https://user-images.githubusercontent.com/71114627/151671436-19923e1d-aedf-49e4-8a80-033a105f2c0f.png)

**Comment by xartd0** [comment]
Уже бул вопрос,посмотри в закрытых issues
