### ISSUE TITLE
Помоги

### ISSUE THREAD

**Issue by maha4kala001** [xartd0/Skysmart-Answers#7]
Помогите пожалуйста выдаёт такую ошибку сделал всё так как ты сказал
![image](https://user-images.githubusercontent.com/98516967/151672936-fea4d764-4ab4-46bc-b5aa-a740186f3db7.png)

**Comment by xartd0** [comment]
Скинь скрин токена из кода и ссылки откуда взял код румы.

**Comment by maha4kala001** [comment]
https://edu.skysmart.ru/student/gohevipukira это ссылка задания скай смарта, токен очень длинный вот часть
![image](https://user-images.githubusercontent.com/98516967/151673513-eca121f7-605c-45e5-9b56-17364c1e0f9f.png)

**Comment by maha4kala001** [comment]
но ссылку учитель поменял вот новая https://edu.skysmart.ru/student/xubonomize

**Comment by xartd0** [comment]
![изображение](https://user-images.githubusercontent.com/43171120/151674135-6c7b1b62-2f65-4df5-b9f3-0ba3821f0563.png)
Перед токеном напиши Bearer

**Comment by maha4kala001** [comment]
Всё равно точно также. Может сюда я не правильно вписал код комнаты? 
![image](https://user-images.githubusercontent.com/98516967/151674288-2e254d75-6b5a-4d34-a01b-69fa06367390.png)

![image](https://user-images.githubusercontent.com/98516967/151674277-3c7df38c-c61e-47c9-81c2-006c20ae10f9.png)

**Comment by xartd0** [comment]
Ты зачем принт делаешь,тебе надо просто запустить скрипт и прямо ввести название или вставить на пустое место,где сейчас ошибка

**Comment by maha4kala001** [comment]
Я убрал что там написал вставил только токен и запустил скрипт и вот что он мне выдаёт, я просто вставляю комнату  и нечего не происходит. Если нажимаю ентер то он закрывается и перед закрытием быстро пишет это
![image](https://user-images.githubusercontent.com/98516967/151689813-e9747145-9df5-4e11-abc0-3624ffaaed6a.png)

![image](https://user-images.githubusercontent.com/98516967/151689758-63372a22-5923-4b59-a806-d3d692892ed9.png)

**Comment by xartd0** [comment]
Если ты не умеешь пользоваться скриптами в питон,используй бота.
