### ISSUE TITLE
Ну это пиздец.

### ISSUE THREAD

**Issue by netstrex** [xartd0/SKYSMART-ANSWERS#8]
Качество кода на уровне👍 Не говоря уже о его функциональности. Во первых токен авторизации можно получить, имея пароль и логин, 1 post запросом, во вторых, я так понимаю при разработке бота использовался aiogram, решение использовать синхронную библиотеку для запросов в интернет, при том что фреймворк асинхронный выше всяких похвал. Повезло что в aiogram встроен отловщик ошибок, иначе 2 одновременно отправленных теста вопросов на 100, положиди бы бота. Боюсь что с МЭШ такая же история. Автор этого мракобесия, дам тебе совет иузчи основные концепции ООП и асинхронного программирования. Создай абстрактный класс, определяющий общее поведение для МЭШ и СкайСмарт, создавай отдельные классы для работы с сетью, то есть с их api, и отдельные для вычисления ответов, после создай не большой класс, через который бот и будет получать ответы. Этот класс будет определять поведение, что если это скайсмарт и что если это МЭШ. Тогда твой код станет производительным, хорошо читаемым, не блокирующим основной поток, который будет обслуживать других пользователей, пока тебе отвечают сервера, и легко расширяемым.

**Comment by xartd0** [comment]
Чел,я конечно понимаю все,но я этот код написал по фану за два часа,и он вообще не был рассчитан для бота,тем более асинхронного, я этим проектом давно не занимаюсь и не поддерживаю код,бота держу чисто,потому что много людей им пользуются. Я и не спорю,что код мусор,если бы я занимался этим проектом реально,я бы все давно переделал.

**Comment by Tomloyo** [comment]
за 2 часа 🔥🤯
